# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2b4167bb53c6963cb57a6d4fdec6f954be37668a8cbee27f3ae0f44599050f091752ec488c31ba62a5724c36bfd23b0df43e11cbf388098f560e01a58edb71a

test:
  secret_key_base: a333d82d4e2584ee4737a5c13389e5b0cb5217bea9b9027a6305b17a438878633068911201e038e2a9184b96b485e904f5753a71e3518b5cce44af91ea875f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
